// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"reggie/internal/dal/model"
)

func newOrder(db *gorm.DB, opts ...gen.DOOption) order {
	_order := order{}

	_order.orderDo.UseDB(db, opts...)
	_order.orderDo.UseModel(&model.Order{})

	tableName := _order.orderDo.TableName()
	_order.ALL = field.NewAsterisk(tableName)
	_order.ID = field.NewInt64(tableName, "id")
	_order.Number = field.NewString(tableName, "number")
	_order.Status = field.NewInt32(tableName, "status")
	_order.UserID = field.NewInt64(tableName, "user_id")
	_order.AddressBookID = field.NewInt64(tableName, "address_book_id")
	_order.OrderTime = field.NewTime(tableName, "order_time")
	_order.CheckoutTime = field.NewTime(tableName, "checkout_time")
	_order.PayMethod = field.NewInt32(tableName, "pay_method")
	_order.PayStatus = field.NewInt32(tableName, "pay_status")
	_order.Amount = field.NewFloat64(tableName, "amount")
	_order.Remark = field.NewString(tableName, "remark")
	_order.Phone = field.NewString(tableName, "phone")
	_order.Address = field.NewString(tableName, "address")
	_order.UserName = field.NewString(tableName, "user_name")
	_order.Consignee = field.NewString(tableName, "consignee")
	_order.CancelReason = field.NewString(tableName, "cancel_reason")
	_order.RejectionReason = field.NewString(tableName, "rejection_reason")
	_order.CancelTime = field.NewTime(tableName, "cancel_time")
	_order.EstimatedDeliveryTime = field.NewTime(tableName, "estimated_delivery_time")
	_order.DeliveryStatus = field.NewBool(tableName, "delivery_status")
	_order.DeliveryTime = field.NewTime(tableName, "delivery_time")
	_order.PackAmount = field.NewInt32(tableName, "pack_amount")
	_order.TablewareNumber = field.NewInt32(tableName, "tableware_number")
	_order.TablewareStatus = field.NewBool(tableName, "tableware_status")

	_order.fillFieldMap()

	return _order
}

// order 订单表
type order struct {
	orderDo orderDo

	ALL                   field.Asterisk
	ID                    field.Int64   // 主键
	Number                field.String  // 订单号
	Status                field.Int32   // 订单状态 1待付款 2待接单 3已接单 4派送中 5已完成 6已取消 7退款
	UserID                field.Int64   // 下单用户
	AddressBookID         field.Int64   // 地址id
	OrderTime             field.Time    // 下单时间
	CheckoutTime          field.Time    // 结账时间
	PayMethod             field.Int32   // 支付方式 1微信,2支付宝
	PayStatus             field.Int32   // 支付状态 0未支付 1已支付 2退款
	Amount                field.Float64 // 实收金额
	Remark                field.String  // 备注
	Phone                 field.String  // 手机号
	Address               field.String  // 地址
	UserName              field.String  // 用户名称
	Consignee             field.String  // 收货人
	CancelReason          field.String  // 订单取消原因
	RejectionReason       field.String  // 订单拒绝原因
	CancelTime            field.Time    // 订单取消时间
	EstimatedDeliveryTime field.Time    // 预计送达时间
	DeliveryStatus        field.Bool    // 配送状态  1立即送出  0选择具体时间
	DeliveryTime          field.Time    // 送达时间
	PackAmount            field.Int32   // 打包费
	TablewareNumber       field.Int32   // 餐具数量
	TablewareStatus       field.Bool    // 餐具数量状态  1按餐量提供  0选择具体数量

	fieldMap map[string]field.Expr
}

func (o order) Table(newTableName string) *order {
	o.orderDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o order) As(alias string) *order {
	o.orderDo.DO = *(o.orderDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *order) updateTableName(table string) *order {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.Number = field.NewString(table, "number")
	o.Status = field.NewInt32(table, "status")
	o.UserID = field.NewInt64(table, "user_id")
	o.AddressBookID = field.NewInt64(table, "address_book_id")
	o.OrderTime = field.NewTime(table, "order_time")
	o.CheckoutTime = field.NewTime(table, "checkout_time")
	o.PayMethod = field.NewInt32(table, "pay_method")
	o.PayStatus = field.NewInt32(table, "pay_status")
	o.Amount = field.NewFloat64(table, "amount")
	o.Remark = field.NewString(table, "remark")
	o.Phone = field.NewString(table, "phone")
	o.Address = field.NewString(table, "address")
	o.UserName = field.NewString(table, "user_name")
	o.Consignee = field.NewString(table, "consignee")
	o.CancelReason = field.NewString(table, "cancel_reason")
	o.RejectionReason = field.NewString(table, "rejection_reason")
	o.CancelTime = field.NewTime(table, "cancel_time")
	o.EstimatedDeliveryTime = field.NewTime(table, "estimated_delivery_time")
	o.DeliveryStatus = field.NewBool(table, "delivery_status")
	o.DeliveryTime = field.NewTime(table, "delivery_time")
	o.PackAmount = field.NewInt32(table, "pack_amount")
	o.TablewareNumber = field.NewInt32(table, "tableware_number")
	o.TablewareStatus = field.NewBool(table, "tableware_status")

	o.fillFieldMap()

	return o
}

func (o *order) WithContext(ctx context.Context) *orderDo { return o.orderDo.WithContext(ctx) }

func (o order) TableName() string { return o.orderDo.TableName() }

func (o order) Alias() string { return o.orderDo.Alias() }

func (o order) Columns(cols ...field.Expr) gen.Columns { return o.orderDo.Columns(cols...) }

func (o *order) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *order) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 24)
	o.fieldMap["id"] = o.ID
	o.fieldMap["number"] = o.Number
	o.fieldMap["status"] = o.Status
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["address_book_id"] = o.AddressBookID
	o.fieldMap["order_time"] = o.OrderTime
	o.fieldMap["checkout_time"] = o.CheckoutTime
	o.fieldMap["pay_method"] = o.PayMethod
	o.fieldMap["pay_status"] = o.PayStatus
	o.fieldMap["amount"] = o.Amount
	o.fieldMap["remark"] = o.Remark
	o.fieldMap["phone"] = o.Phone
	o.fieldMap["address"] = o.Address
	o.fieldMap["user_name"] = o.UserName
	o.fieldMap["consignee"] = o.Consignee
	o.fieldMap["cancel_reason"] = o.CancelReason
	o.fieldMap["rejection_reason"] = o.RejectionReason
	o.fieldMap["cancel_time"] = o.CancelTime
	o.fieldMap["estimated_delivery_time"] = o.EstimatedDeliveryTime
	o.fieldMap["delivery_status"] = o.DeliveryStatus
	o.fieldMap["delivery_time"] = o.DeliveryTime
	o.fieldMap["pack_amount"] = o.PackAmount
	o.fieldMap["tableware_number"] = o.TablewareNumber
	o.fieldMap["tableware_status"] = o.TablewareStatus
}

func (o order) clone(db *gorm.DB) order {
	o.orderDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o order) replaceDB(db *gorm.DB) order {
	o.orderDo.ReplaceDB(db)
	return o
}

type orderDo struct{ gen.DO }

func (o orderDo) Debug() *orderDo {
	return o.withDO(o.DO.Debug())
}

func (o orderDo) WithContext(ctx context.Context) *orderDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderDo) ReadDB() *orderDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderDo) WriteDB() *orderDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderDo) Session(config *gorm.Session) *orderDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderDo) Clauses(conds ...clause.Expression) *orderDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderDo) Returning(value interface{}, columns ...string) *orderDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderDo) Not(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderDo) Or(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderDo) Select(conds ...field.Expr) *orderDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderDo) Where(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderDo) Order(conds ...field.Expr) *orderDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderDo) Distinct(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderDo) Omit(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderDo) Join(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderDo) Group(cols ...field.Expr) *orderDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderDo) Having(conds ...gen.Condition) *orderDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderDo) Limit(limit int) *orderDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderDo) Offset(offset int) *orderDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderDo) Unscoped() *orderDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderDo) Create(values ...*model.Order) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderDo) CreateInBatches(values []*model.Order, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderDo) Save(values ...*model.Order) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderDo) First() (*model.Order, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Take() (*model.Order, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Last() (*model.Order, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) Find() ([]*model.Order, error) {
	result, err := o.DO.Find()
	return result.([]*model.Order), err
}

func (o orderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Order, err error) {
	buf := make([]*model.Order, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderDo) FindInBatches(result *[]*model.Order, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderDo) Attrs(attrs ...field.AssignExpr) *orderDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderDo) Assign(attrs ...field.AssignExpr) *orderDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderDo) Joins(fields ...field.RelationField) *orderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderDo) Preload(fields ...field.RelationField) *orderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderDo) FirstOrInit() (*model.Order, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) FirstOrCreate() (*model.Order, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Order), nil
	}
}

func (o orderDo) FindByPage(offset int, limit int) (result []*model.Order, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderDo) Delete(models ...*model.Order) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderDo) withDO(do gen.Dao) *orderDo {
	o.DO = *do.(*gen.DO)
	return o
}
