// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddressBook = "address_book"

// AddressBook 地址簿
type AddressBook struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`   // 主键
	UserID       int64  `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`            // 用户id
	Consignee    string `gorm:"column:consignee;comment:收货人" json:"consignee"`                  // 收货人
	Sex          string `gorm:"column:sex;comment:性别" json:"sex"`                               // 性别
	Phone        string `gorm:"column:phone;not null;comment:手机号" json:"phone"`                 // 手机号
	ProvinceCode string `gorm:"column:province_code;comment:省级区划编号" json:"province_code"`       // 省级区划编号
	ProvinceName string `gorm:"column:province_name;comment:省级名称" json:"province_name"`         // 省级名称
	CityCode     string `gorm:"column:city_code;comment:市级区划编号" json:"city_code"`               // 市级区划编号
	CityName     string `gorm:"column:city_name;comment:市级名称" json:"city_name"`                 // 市级名称
	DistrictCode string `gorm:"column:district_code;comment:区级区划编号" json:"district_code"`       // 区级区划编号
	DistrictName string `gorm:"column:district_name;comment:区级名称" json:"district_name"`         // 区级名称
	Detail       string `gorm:"column:detail;comment:详细地址" json:"detail"`                       // 详细地址
	Label        string `gorm:"column:label;comment:标签" json:"label"`                           // 标签
	IsDefault    bool   `gorm:"column:is_default;not null;comment:默认 0 否 1是" json:"is_default"` // 默认 0 否 1是
}

// TableName AddressBook's table name
func (*AddressBook) TableName() string {
	return TableNameAddressBook
}
