// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSetmeal = "setmeal"

// Setmeal 套餐
type Setmeal struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`  // 主键
	CategoryID  int64     `gorm:"column:category_id;not null;comment:菜品分类id" json:"category_id"` // 菜品分类id
	Name        string    `gorm:"column:name;not null;comment:套餐名称" json:"name"`                 // 套餐名称
	Price       float64   `gorm:"column:price;not null;comment:套餐价格" json:"price"`               // 套餐价格
	Status      int32     `gorm:"column:status;default:1;comment:售卖状态 0:停售 1:起售" json:"status"`  // 售卖状态 0:停售 1:起售
	Description string    `gorm:"column:description;comment:描述信息" json:"description"`            // 描述信息
	Image       string    `gorm:"column:image;comment:图片" json:"image"`                          // 图片
	CreateTime  time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`            // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`            // 更新时间
	CreateUser  int64     `gorm:"column:create_user;comment:创建人" json:"create_user"`             // 创建人
	UpdateUser  int64     `gorm:"column:update_user;comment:修改人" json:"update_user"`             // 修改人
}

// TableName Setmeal's table name
func (*Setmeal) TableName() string {
	return TableNameSetmeal
}
