// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDishFlavor = "dish_flavor"

// DishFlavor 菜品口味关系表
type DishFlavor struct {
	ID     int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	DishID int64  `gorm:"column:dish_id;type:bigint;not null;comment:菜品" json:"dish_id"`            // 菜品
	Name   string `gorm:"column:name;type:varchar(32);comment:口味名称" json:"name"`                    // 口味名称
	Value  string `gorm:"column:value;type:varchar(255);comment:口味数据list" json:"value"`             // 口味数据list
}

// TableName DishFlavor's table name
func (*DishFlavor) TableName() string {
	return TableNameDishFlavor
}
