// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderDetail = "order_detail"

// OrderDetail 订单明细表
type OrderDetail struct {
	ID         int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name       string  `gorm:"column:name;type:varchar(32);comment:名字" json:"name"`                      // 名字
	Image      string  `gorm:"column:image;type:varchar(255);comment:图片" json:"image"`                   // 图片
	OrderID    int64   `gorm:"column:order_id;type:bigint;not null;comment:订单id" json:"order_id"`        // 订单id
	DishID     int64   `gorm:"column:dish_id;type:bigint;comment:菜品id" json:"dish_id"`                   // 菜品id
	SetmealID  int64   `gorm:"column:setmeal_id;type:bigint;comment:套餐id" json:"setmeal_id"`             // 套餐id
	DishFlavor string  `gorm:"column:dish_flavor;type:varchar(50);comment:口味" json:"dish_flavor"`        // 口味
	Number     int32   `gorm:"column:number;type:int;not null;default:1;comment:数量" json:"number"`       // 数量
	Amount     float64 `gorm:"column:amount;type:decimal(10,2);not null;comment:金额" json:"amount"`       // 金额
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
