// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户信息
type User struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Openid     string    `gorm:"column:openid;type:varchar(45);comment:微信用户唯一标识" json:"openid"`            // 微信用户唯一标识
	Name       string    `gorm:"column:name;type:varchar(32);comment:姓名" json:"name"`                      // 姓名
	Phone      string    `gorm:"column:phone;type:varchar(11);comment:手机号" json:"phone"`                   // 手机号
	Sex        string    `gorm:"column:sex;type:varchar(2);comment:性别" json:"sex"`                         // 性别
	IDNumber   string    `gorm:"column:id_number;type:varchar(18);comment:身份证号" json:"id_number"`          // 身份证号
	Avatar     string    `gorm:"column:avatar;type:varchar(500);comment:头像" json:"avatar"`                 // 头像
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
