basePath: /
host: localhost:8080
info:
  contact:
    name: onenewcode
    url: https://github.com/onenewcode
  description: sky-take-out
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: regiee
  version: "0.1"
paths:
  /admin/employee:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 存储用户
schemes:
- http
swagger: "2.0"
